### ISSUE TITLE
chore: release process automation

### ISSUE THREAD

**Issue by getlarge** [planetmint/planetmint-driver-ts#6]
# Description

Since we do not allow push on main, which is a good thing, we are also stuck during release process as we cannot push the changed version (in package.json for instance).
To avoid giving and managing access rights for individual users, we could use a custom GH action workflow that would be responsible for release. We could trigger it manually and/or after a successful merge to main.
This workflow would authenticate with a service user or bot assigned to a team in planetmint org, and it would have necessary grants to push on main.

@eckelj could you create such a user with enough rights ?
Also we would need an access token (with the correct access rights obviously) from that user to use it in the workflow.

**Comment by eckelj** [comment]
@getlarge sure! I think that this is a good thing! We use tagging with a dedicated scheme to init the package publishing: 
https://github.com/planetmint/planetmint-driver-python/blob/861d15d9274f6ad14b47657ba5002495a32853dc/.github/workflows/CI.yml#L78

We would just need to have a release task for NPM. do you have an example that you prefer and suggest?

**Comment by getlarge** [comment]
We already have some things ready in the repo using the command [`npm run release`](https://github.com/planetmint/planetmint-driver-ts/blob/main/package.json#L34), which uses `release-it` lib under the hood. That's what i've been using to create the tag and the release on NPM but got stuck to release on GH as i was missing some access rights.

A practice that i like, is to use the [conventional commits specs](https://www.conventionalcommits.org/en/v1.0.0/) to determine the bump (patch, minor, major) and generate the changelog.
And fortunately there's a [good plugin](https://github.com/release-it/conventional-changelog) for `release-it` to manage that for us.
So an approach i would like to follow would be :
- add pre-commit hooks to validate commit messages (using conventional commits)
- when PR gets merged successfully, a dedicated job or workflow gets triggered to bump version, generate changelog, create tag and releases.
